import baseStreamDoc from "./assets/base-stream-doc.pdf";

export const docTemplate = {
	schemas: [
		{
			name: {
				type: "text",
				position: {
					x: 25.34,
					y: 73.41,
				},
				width: 117.02,
				height: 7,
				alignment: "left",
				fontSize: 12,
				characterSpacing: 0,
				lineHeight: 1,
				backgroundColor: "#ffffff",
			},
			"total amount": {
				type: "text",
				position: {
					x: 25.34,
					y: 89.69,
				},
				width: 75.74,
				height: 7,
				alignment: "left",
				fontSize: 12,
				characterSpacing: 0,
				lineHeight: 1,
				backgroundColor: "#ffffff",
			},
			"release frequency": {
				type: "text",
				position: {
					x: 25.34,
					y: 105.3,
				},
				width: 35,
				height: 7,
				alignment: "left",
				fontSize: 12,
				characterSpacing: 0,
				lineHeight: 1,
				backgroundColor: "#ffffff",
			},
			"sender wallet": {
				type: "text",
				position: {
					x: 25.34,
					y: 121.44,
				},
				width: 140,
				height: 7,
				alignment: "left",
				fontSize: 12,
				characterSpacing: 0,
				lineHeight: 1,
				backgroundColor: "#ffffff",
			},
			"recipient wallet": {
				type: "text",
				position: {
					x: 25.34,
					y: 137.52,
				},
				width: 140,
				height: 7,
				alignment: "left",
				fontSize: 12,
				characterSpacing: 0,
				lineHeight: 1,
				backgroundColor: "#ffffff",
			},
			"start date": {
				type: "text",
				position: {
					x: 25.34,
					y: 153.66,
				},
				width: 35,
				height: 7,
				alignment: "left",
				fontSize: 12,
				characterSpacing: 0,
				lineHeight: 1,
				backgroundColor: "#ffffff",
			},
			"end date": {
				type: "text",
				position: {
					x: 25.34,
					y: 169.27,
				},
				width: 35,
				height: 7,
				alignment: "left",
				fontSize: 12,
				characterSpacing: 0,
				lineHeight: 1,
				backgroundColor: "#ffffff",
			},
			"stream status": {
				type: "text",
				position: {
					x: 25.34,
					y: 185.74,
				},
				width: 35,
				height: 7,
				alignment: "left",
				fontSize: 12,
				characterSpacing: 0,
				lineHeight: 1,
				backgroundColor: "#ffffff",
			},
			"stream direction": {
				type: "text",
				position: {
					x: 25.34,
					y: 201.35,
				},
				width: 35,
				height: 7,
				alignment: "left",
				fontSize: 12,
				characterSpacing: 0,
				lineHeight: 1,
				backgroundColor: "#ffffff",
			},
			"automatic withdrawal": {
				type: "text",
				position: {
					x: 25.34,
					y: 218.55,
				},
				width: 35,
				height: 7,
				alignment: "left",
				fontSize: 12,
				characterSpacing: 0,
				lineHeight: 1,
				backgroundColor: "#ffffff",
			},
		},
	],
	basePdf: baseStreamDoc,
};
